### ISSUE TITLE
PF goes to Admin Login Page

### ISSUE THREAD

**Issue by LarryGrim** [pentestgeek/phishing-frenzy#348]
Still in Development mode.
Launch Campaign
Receipent clicks on link.
Presented with Admin Login Page instead of campaign page
Attached is output from end of /etc/apache2/apache2.conf; the command "apachectl -S"; contents of pf.conf.
[Issue - Grim.txt](https://github.com/pentestgeek/phishing-frenzy/files/601601/Issue.-.Grim.txt)

**Comment by LarryGrim** [comment]
Checking with the two URLs in troubleshooting also fails.
![issue-grim](https://cloud.githubusercontent.com/assets/14098032/20457646/953d2ece-ae5d-11e6-8b4b-a403ef14b3e5.png)

**Comment by zeknox** [comment]
Pretty sure this has been resolved somewhere down the line, re-open if needed.

**Comment by zeknox** [comment]
I'm not sure if this is related or not, but it looks like it's redirecting to the login page due to using the same FQDN for campaign 2, and the PF interface.

Looking at the apache output as seen below, once you enabled the campaign it's hitting the `pf.conf` VHOST first and serving up the login page.
<pre>
         port 80 namevhost provider-resource.com (/etc/apache2/pf.conf:1)
         port 80 namevhost provider-resource.com (/etc/apache2/sites-enabled/2.conf:2)
</pre>

Good feedback on the the /reports routes that don't seem to be aligning properly.  We'll try to investigate and ensure it's operating as expected.

**Comment by LarryGrim** [comment]
Wonderful.  Any additional data/logs/etc that might help, please let me know. As a suggestion, it might be useful to have a basic data-dump outline accompany most issues tickets.
/r

**Comment by zeknox** [comment]
All of the logs should be accumulating within `/var/www/phishing-frenzy/logs/*`, I don't anticipate they'll yield anything really useful.  This looks like you have 2 websites with the same FQDN and Apache is simply serving up the first one in the list.

**Comment by LarryGrim** [comment]
Actually, it is interesting what the launched campaign actually provides as a link
![pf 11-22-2016](https://cloud.githubusercontent.com/assets/14098032/20568283/fa1c9726-b169-11e6-8b01-464c85472180.png)
Attached are the Apache conf files (apache2.conf, pf.conf, sites-enabled/2.conf) as well as the logs www-campaign-2-access.log.  The pf campaign 2 error log is 0 bytes.
[PF 11-23-2106.txt](https://github.com/pentestgeek/phishing-frenzy/files/609275/PF.11-23-2106.txt)

**Comment by zeknox** [comment]
The launched campaign should be getting the phishing URL based on what you defined within the campaign settings, or unless you hardcoded it within the phishing template email.  Checkout your "Phishing URL" first within campaign settings and see if thats where this URL is coming from.

**Comment by LarryGrim** [comment]
hmm.. phishing URL is just the FQDN (provider-resource.com).  Me thinks that is not correct?

**Comment by zeknox** [comment]
Right above FQDN should be Phishing URL option as well.  They are similar but actually a bit different.  The Phishing URL is what actually gets put within the email, whereas FQDN is the domain that is used to configure apache to server up the phishing site.  So they are a lil diff.

**Comment by LarryGrim** [comment]
FQDN and Phishing URL are both provider-resource.com
Phishing URL should be ?  
[probably RTFM, someplace, eh?]

**Comment by zeknox** [comment]
The idea is that these can be anything you like.  You'll want to make sure you own the domain that your setting up for the FQDN and the Phishing URL, and configure your public DNS to point the A record to the public IP address of the PF box.

This way when you activate the campaign (or launch) it will configure Apache with the FQDN you have defined, DNS will point the name to the PF server, and then your phishing site will be served up.

I guess I'm struggling to understand what your issue is because the URL is suppose to be whatever you define within the campaign.

**Comment by LarryGrim** [comment]
Oh, so the entry for the phishing URL must have /index.php, such as the example of intel.domain.com/index.php in your video?  As I have the FQDN of provider-resource.com, the phishig URL must be provider-resource.com/index.php?   Could the displayed (not linked) phishing link be stupid.guy/index.php?

**Comment by zeknox** [comment]
The Phishing URL should be a full url like `https://contoso.loc/` as long as the template has a default Index file of index.php for example, then you dont even need to append that at the end of the url.  The FQDN does not have the HTTP or HTTPS portion, but rather only the FQDN like `contoso.loc` if that is what you want Apache to use for a domain.

**Comment by LarryGrim** [comment]
Here is the setup that still has the phish URL (http://provider-resource.com/?uid=FRTYZOTC) going to the admin login page:
![pf-11-23-2016](https://cloud.githubusercontent.com/assets/14098032/20569667/de986cdc-b16e-11e6-85d6-fb871476e12c.png)

**Comment by zeknox** [comment]
Is provider-resource.com the same URL you are leveraging for the PF UI?

**Comment by LarryGrim** [comment]
Yes.  I thought that the Phishing URL had to be in a domain that I controlled.   Are you suggesting that it could be/should be something else, such as http://intel.domain.com/  ??/

**Comment by zeknox** [comment]
Yes, thats precisely what I'm recommending. So sorry if this was not clear, but you're going to want a domain for the PF UI, and a separate domain for your phishing sites. This is so you have unique urls essentially so Apache knows what website it should show the browser when requests come in.

You're issue should be solved once you create separate FQDNs for the PF UI and a separate FQDN for a campaign.  Sorry for any inconvenience, but this is going to allow for added flexibility to allow your phishing site to be anything you want it to be.

**Comment by LarryGrim** [comment]
Still having the "victim" going to the admin login page.
ok.  When I put in different domains that I control, build a new campaign, use one domain for the phishing URL and the other for the FQDN, still goes to the admin URL.
![pf-11-23b-2016](https://cloud.githubusercontent.com/assets/14098032/20571118/3d116912-b174-11e6-9421-26fb51c010f7.png)
![pf-11-23c-2016](https://cloud.githubusercontent.com/assets/14098032/20571131/476d6474-b174-11e6-9046-1920d72f9dd0.png)
And the 3.conf file does not reflect the provider---resources.com domain anywhere.
![pf-11-23d-2016](https://cloud.githubusercontent.com/assets/14098032/20571226/96edcf7a-b174-11e6-8b82-418121afb7d1.png)

**Comment by zeknox** [comment]
Can you show me the output of `apachectl -S` again now that you've made some changes.  Thanks.

**Comment by LarryGrim** [comment]
![pf-11-23e-2016](https://cloud.githubusercontent.com/assets/14098032/20571594/1ac3cf1a-b176-11e6-8996-aa019687db12.png)

**Comment by zeknox** [comment]
Yeah, so you've still got the same problem from the original post where pf.conf, 2.conf, 3.conf all have the same FQDN. Look at this for a moment and think, how is Apache suppose to show the phishing site on campaign 2 or campaign 3 if the FQDN is identical on all 3 websites.

You need these FQDNs to be unique before anything is going to work.  Continue to modify until this command is showing different FQDNs for each VHOST entry.

**Comment by zeknox** [comment]
It might be that you updated the campaign with a new FQDN, but you need to make campaign in-active, save, then make it active again until these changes are shown within the Apache output command.

**Comment by LarryGrim** [comment]
Made all campaigns inactive.
![pf-11-23h-2016](https://cloud.githubusercontent.com/assets/14098032/20572485/a6029b9e-b179-11e6-807b-9caf08974114.png)
The screen shows the status after all inactive, and when campaign 3 was made active, as well as the contents of the new 3.conf
![pf-11-23g-2016](https://cloud.githubusercontent.com/assets/14098032/20572510/bfa2d906-b179-11e6-838f-ec3ec0f418a1.png)

Still has the victim going to the admin login screen, though the URL in the email shows:
http://provider---resources.com/?uid=XWCMOPRZ

The output for apachectl -S at this stage is:
![pf-11-23i-2016](https://cloud.githubusercontent.com/assets/14098032/20572597/1c351846-b17a-11e6-8ad9-307639378e1c.png)

**Comment by zeknox** [comment]
Campaign 3 seems to have a FQDN of `provider-resource.com` within the Campaign Settings?  Is that correct or not.  3.conf is populated based on campaign settings.

**Comment by LarryGrim** [comment]
yes.
and when I create a 4.conf, with the correct ServerAlias, the URL provided in the email changes
![pf-11-23j-2016](https://cloud.githubusercontent.com/assets/14098032/20573029/f1ddc582-b17b-11e6-83da-a1af73347788.png)
However, Kaspersky blocks it
![pf-11-23k-2016](https://cloud.githubusercontent.com/assets/14098032/20573045/01c34e54-b17c-11e6-9b1b-69ac5fa0a562.png)
and pausing the protection from Kaspersky, the email phishing URL gives an error page (still in DEVELOPMENT mode)
![pf-11-23l-2016](https://cloud.githubusercontent.com/assets/14098032/20573067/1a701842-b17c-11e6-8649-2d77ec7b790d.png)

with manually creating tne conf file, it gets better, but not working as expected.

**Comment by LarryGrim** [comment]
argh!  your question was the 3.conf contents after the deactiivate/reactivate.  Sorry.
![pf-11-23m-2016](https://cloud.githubusercontent.com/assets/14098032/20573170/92a14066-b17c-11e6-86a4-4e4285b88f52.png)

**Comment by zeknox** [comment]
Any updates here if you're able to get everything working properly now that you have 2 seperate VHOST FQDNs configure it looks like?

**Comment by LarryGrim** [comment]
No change.  Even with a manually created 4.conf it failed.

**Comment by zeknox** [comment]
Based on one of the screenshots above your PHP is not rendering properly.  The screenshot which is white and starts with the PHP tag shows me that PHP does not know how to render it properly.

**Comment by LarryGrim** [comment]
That was the page that came up in response to a "victim" selecting the link (URL has the ?uid=).
What would be my next step?  So close.

**Comment by zeknox** [comment]
Yes, that proves that it's loading the phishing site because those PHP tags are appended to the top of all phishing pages, this block of PHP is how PF is able to track analytics.  So the white page is your phishing site, its just not loading the PHP properly it appears.

**Comment by LarryGrim** [comment]
yes. It just returned the page of code, that I just capture the first part.  It did not register any actions on the part of the "victim": opened, etc.

**Comment by zeknox** [comment]
It will never register any actions because again, this is the code which is used for all the tracking analytics... PHP don't render properly, you have no analytics...

**Comment by LarryGrim** [comment]
what is next step?  is there a check of the php? passenger? something to mend the broken system?

**Comment by zeknox** [comment]
Is the website file within your phishing template ending in a .php extension like stated in the docs?  Is PHP package installed properly on the OS?

**Comment by LarryGrim** [comment]
Yes.   Setup again, using the eFax template in the installation package.   Got the page of php code.   Here is the apachectl -S, the 4.conf for the apache config, and the contents of the phishing site directory.

![image](https://cloud.githubusercontent.com/assets/14098032/20685824/fc02e20c-b583-11e6-964d-6c205223dabe.png)

**Comment by zeknox** [comment]
Type `php login.php` within that directory and see what the output is.

**Comment by LarryGrim** [comment]
![image](https://cloud.githubusercontent.com/assets/14098032/20687845/1937b390-b58c-11e6-830a-86f5e12b0b1e.png)

**Comment by LarryGrim** [comment]
Hmm.. there may be no php modules enabled.
directory of the /etc/apache2/mods-enabled is 
![image](https://cloud.githubusercontent.com/assets/14098032/20688038/0a7ef696-b58d-11e6-9c70-03ae3c1cff6c.png)

while /etc/apache2/mods-available is
![image](https://cloud.githubusercontent.com/assets/14098032/20688059/2649e818-b58d-11e6-91aa-896c209e85ee.png)

**Comment by zeknox** [comment]
Yeah I was just going to say that Apache doesn't seem to have PHP working properly.  The command `php` is working based on your output above.  Look at enabling the module and restarting the apache service.

**Comment by LarryGrim** [comment]
Yes.  that was it.  Now working with the LinkedIn template, as well as the two (Intel/eFax) from the installation package.  Do not know why php apache module did not load but php was on the system. 
Thank you.

**Comment by zeknox** [comment]
Awesome, nice work!

**Comment by zeknox** [comment]
Issue Resolved.
